name: build-artifacts

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2.1.0
        with:
          distribution: 'adopt'
          java-version: 8

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build artifacts
        run: ./gradlew clean build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2.2.3
        with:
          name: build-artifacts
          path: build/libs
